trigger:
- main

pool: local-agent

resources:
- repo: self

variables:
  - group: CICD
  - name: app_var
    value: $[variables.appVariable]
  
  - group: CICD
  - name: arcUser
    value: $[variables.acrUsername]
  
  - group: CICD
  - name: arcPWD
    value: $[variables.acrPassword]

parameters:
  - name: tag
    default: "$(Build.BuildId)"
  - name: imageName
    default: "public-api"
  
  #Valores anteriores
  #tag: '$(Build.BuildId)'
  #imageName: 'public-api'
  #vmImageName: ubuntu-latest

stages: #En Github actions esto se llama jobs
- stage: Build
  displayName: Build image
  jobs: #En GitHub actions se llama steps
  - job: Build
    displayName: Build
    #pool:
    #  vmImage: $(vmImageName)

    steps:
    - script: |
        echo "var=$(app_var)"
    - task: Docker@2
      displayName: Build an image
      inputs:
        repository: ${{ parameters.imageName }}
        command: build
        containerRegistry: 'registryConnection'
        dockerfile: "**/qa.dockerfile"
        tags: ${{ parameters.tag }}
        arguments: '--build-arg APP_ENV=$(app_var)'
        
        #repository: $(imageName)
        #command: build
        #dockerfile: '**/qa.dockerfile'
        #tags: |
        #  $(tag)

    - task: Docker@2
      displayName: 'Push Docker Image'
      inputs:
        command: 'push'
        containerRegistry: 'registryConnection'
        repository: ${{ parameters.imageName }}
        tags: |
          ${{ parameters.tag }}
  - job: Deploy
    displayName: Deploy
    dependsOn: Build
    steps:
      - task: AzureContainerApps@1
        inputs:
          #Nombre de conector creado en ADS para pegar con webApps
          azureSubscription: 'appDeployConnection'
          imageToDeploy: acrappsJorge.azurecr.io/${{ parameters.imageName }}:$(Build.BuildId)
          containerAppName: 'app-public-api-jorge' # NOMBRE DEL CONTAINER APP
          resourceGroup: rg-jorge
          acrUsername: $(arcUser)
          acrPassword: $(arcPWD)


