trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  imageName: 'public-api'
  vmImageName: ubuntu-latest

stages: #En Github actions esto se llama jobs
- stage: Build
  displayName: Build image
  jobs: #En GitHub actions se llama steps
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)

    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        repository: $(imageName)
        command: build
        dockerfile: '**/qa.dockerfile'
        tags: |
          $(tag)
